# Generated by Django 3.1.7 on 2021-04-04 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msa_app', '0005_auto_20210404_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='vendor_id',
            field=models.CharField(default='VEN', max_length=10),
        ),
    ]
